version: 3.0.{build}
configuration: Release
nuget:
  disable_publish_on_pr: true
build_script:
- cmd: build.cmd /tv:14.0 /p:VisualStudioVersion=14.0 /p:ToolsVersion=14.0
artifacts:
- path: '**\app.publish\*.cspkg'
- path: '**\app.publish\*.nupkg'
